export const data = [
    {
        text: "LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA.",
        date: "Rajan Mcclure, 5 months ago"
    },
    {
        text: "TURPIS NUNC EGET LOREM DOLOR SED VIVERRA. TINCIDUNT LOBORTIS FEUGIAT VIVAMUS AT AUGUE EGET ARCU VOLUTPAT SED CRAS ORNARE",
        date: "Jean Walls, 5 months ago"
    },
    {
        text: "LACUS VEL FACILISIS VOLUTPAT EST VELIT EGESTAS DUI ID. NON PULVINAR NEQUE LAOREET SUSPENDISSE INTERDUM CONSECTETUR LIBERO",
        date: "Wyatt Benson, 5 months ago"
    },
    {
        text: "LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA.",
        date: "Rajan Mcclure, 5 months ago"
    }
]